# Generated by Django 4.1.10 on 2023-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problems',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('adminEmail', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('question', models.CharField(max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcases',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('adminEmail', models.CharField(max_length=300, null=True)),
                ('input', models.CharField(max_length=10000, null=True)),
                ('output', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
